#include <QApplication>
#include <QPushButton>
#include <iostream>

#include "repository.h"
#include "service.h"
#include "posts_ui.h"

int main(int argc, char *argv[]) {
    Repository<Post> repository;
    Service service{repository};
    service.add("The Future of Urban Gardening", "Addison Clarke", "A Look at Vertical Farms and Community Spaces");
    service.add("Traveling on a Budget", "Blake Montgomery", "Top 10 Affordable Destinations for Your Next Adventure");
    service.add("Creating the Perfect Workspace", "Cassidy Reynolds",
                "How to Boost Productivity and Comfort in Your Home Office");
    service.add("The Art of Storytelling", "Dylan Hayes", "Captivating Your Audience Through Narrative Techniques");
    service.add("Exploring the Stars", "Emery Gray", "A Beginner's Guide to Stargazing and Amateur Astronomy");
    service.add("Blog posts by GPT-4", "Mali Imre Gergely", "The above posts were generated by GPT-4");

    QApplication a(argc, argv);
    QApplication::setFont(QFont{"Verdana", 20});
    PostUI ui{service};
    ui.show();
    return QApplication::exec();
}
